name: Build and Push Docker Images

on:
  push:
    branches:
      - master
      - release-*
    tags:
      - "v*"
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  image:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login docker.io
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Show Available Platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Build and Push Docker Images
        run: make container-build-push
